name: ipbjp_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.11.0
  isar: ^3.1.0+1
  logger: ^2.0.2
  uuid: ^4.0.0
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
